# 网站信息
site_name: go-leetcode
site_author: GavinYao
site_description: 'Go With LeetCode'

# 仓库链接
repo_url: https://github.com/yaoguyuan/go-leetcode
repo_name: go-leetcode

# 主题配置
theme:
  name: material
  language: zh
  palette:
    - scheme: default
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: 切换到夜间模式
    - scheme: slate
      primary: deep-purple
      accent: green
      toggle:
        icon: material/brightness-4
        name: 切换到日间模式
  features:
    - navigation.tabs 
    - navigation.sections 
    - navigation.top 
    - search.suggest 
    - search.highlight 
    - content.code.copy 
    - content.code.annotate 

# 导航栏配置
nav:
  - 'Home': 'index.md'
  - 'Hot100': 
    - '哈希表': 
      - 'LC1': 'hot100/hashTable/LC1.md' 
      - 'LC49': 'hot100/hashTable/LC49.md' 
      - 'LC128': 'hot100/hashTable/LC128.md' 
    - '双指针': 
      - 'LC283': 'hot100/doublePointers/LC283.md' 
      - 'LC11': 'hot100/doublePointers/LC11.md' 
      - 'LC15': 'hot100/doublePointers/LC15.md' 
      - 'LC42': 'hot100/doublePointers/LC42.md' 
    - '滑动窗口': 
      - 'LC3': 'hot100/slidingWindow/LC3.md' 
      - 'LC438': 'hot100/slidingWindow/LC438.md' 
    - '子串': 
      - 'LC560': 'hot100/substring/LC560.md' 
      - 'LC239': 'hot100/substring/LC239.md' 
      - 'LC76': 'hot100/substring/LC76.md' 
    - '普通数组': 
      - 'LC53': 'hot100/array/LC53.md'
      - 'LC56': 'hot100/array/LC56.md'
      - 'LC189': 'hot100/array/LC189.md'
      - 'LC238': 'hot100/array/LC238.md'
      - 'LC41': 'hot100/array/LC41.md'
    - '矩阵': 
      - 'LC73': 'hot100/matrix/LC73.md'
      - 'LC54': 'hot100/matrix/LC54.md'
      - 'LC48': 'hot100/matrix/LC48.md'
      - 'LC240': 'hot100/matrix/LC240.md'
    - '链表':
      - 'LC160': 'hot100/linkedList/LC160.md'
      - 'LC206': 'hot100/linkedList/LC206.md'
      - 'LC234': 'hot100/linkedList/LC234.md'
      - 'LC141': 'hot100/linkedList/LC141.md'
      - 'LC142': 'hot100/linkedList/LC142.md'
      - 'LC21': 'hot100/linkedList/LC21.md'
      - 'LC2': 'hot100/linkedList/LC2.md'
      - 'LC19': 'hot100/linkedList/LC19.md'
      - 'LC24': 'hot100/linkedList/LC24.md'
      - 'LC25': 'hot100/linkedList/LC25.md'
      - 'LC138': 'hot100/linkedList/LC138.md'
      - 'LC148': 'hot100/linkedList/LC148.md'
      - 'LC23': 'hot100/linkedList/LC23.md'
      - 'LC146': 'hot100/linkedList/LC146.md'
    - '二叉树':
      - 'LC94': 'hot100/binaryTree/LC94.md'
      - 'LC104': 'hot100/binaryTree/LC104.md'
      - 'LC226': 'hot100/binaryTree/LC226.md'
      - 'LC101': 'hot100/binaryTree/LC101.md'
      - 'LC543': 'hot100/binaryTree/LC543.md'
      - 'LC102': 'hot100/binaryTree/LC102.md'
      - 'LC108': 'hot100/binaryTree/LC108.md'
      - 'LC98': 'hot100/binaryTree/LC98.md'
      - 'LC230': 'hot100/binaryTree/LC230.md'
      - 'LC199': 'hot100/binaryTree/LC199.md'
      - 'LC114': 'hot100/binaryTree/LC114.md'
      - 'LC105': 'hot100/binaryTree/LC105.md'
      - 'LC437': 'hot100/binaryTree/LC437.md'
      - 'LC236': 'hot100/binaryTree/LC236.md'
      - 'LC124': 'hot100/binaryTree/LC124.md'
    - '图论':
      - 'LC200': 'hot100/graph/LC200.md'
      - 'LC994': 'hot100/graph/LC994.md'
      - 'LC207': 'hot100/graph/LC207.md'
      - 'LC208': 'hot100/graph/LC208.md'
    - '回溯':
      - 'LC46': 'hot100/backtrack/LC46.md'
      - 'LC78': 'hot100/backtrack/LC78.md'
      - 'LC17': 'hot100/backtrack/LC17.md'
      - 'LC39': 'hot100/backtrack/LC39.md'
      - 'LC22': 'hot100/backtrack/LC22.md'
      - 'LC79': 'hot100/backtrack/LC79.md'
      - 'LC131': 'hot100/backtrack/LC131.md'
      - 'LC51': 'hot100/backtrack/LC51.md'
    - '二分查找':
      - 'LC35': 'hot100/binarySearch/LC35.md'
      - 'LC74': 'hot100/binarySearch/LC74.md'
      - 'LC34': 'hot100/binarySearch/LC34.md'
      - 'LC33': 'hot100/binarySearch/LC33.md'
      - 'LC153': 'hot100/binarySearch/LC153.md'
      - 'LC4': 'hot100/binarySearch/LC4.md'
    - '栈':
      - 'LC20': 'hot100/stack/LC20.md'
      - 'LC155': 'hot100/stack/LC155.md'
      - 'LC394': 'hot100/stack/LC394.md'
      - 'LC739': 'hot100/stack/LC739.md'
      - 'LC84': 'hot100/stack/LC84.md'
    - '堆':
      - 'LC215': 'hot100/heap/LC215.md'
      - 'LC347': 'hot100/heap/LC347.md'
      - 'LC295': 'hot100/heap/LC295.md'
    - '贪心算法':
      - 'LC121': 'hot100/greedy/LC121.md'
      - 'LC55': 'hot100/greedy/LC55.md'
      - 'LC45': 'hot100/greedy/LC45.md'
      - 'LC763': 'hot100/greedy/LC763.md'

# 扩展配置
markdown_extensions:
  - pymdownx.highlight: 
      anchor_linenums: true 
      line_spans: __span 
      pygments_lang_class: true
  - pymdownx.inlinehilite 
  - pymdownx.snippets 
  - pymdownx.superfences 
  - pymdownx.details 
  - pymdownx.arithmatex: 
      generic: true
  - pymdownx.tabbed: 
      alternate_style: true

  - admonition 
  - footnotes 
  - attr_list 
  - md_in_html

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML